version: "3.7"

services:
  minio:
    image: quay.io/minio/minio:latest
    command: server --console-address ":9001" /data
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: miniominio
      MINIO_ROOT_PASSWORD:  miniominio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 20s
      timeout: 10s
      retries: 3
    volumes:
      - data:/data
    networks:
      - objects
  aws:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/test.bash:/tmp/test.bash
    command: /tmp/test.bash
    networks:
      - objects

networks:
  objects:
volumes:
  data:
      # aws s3api create-bucket \
      # --endpoint-url http://localhost:9000/ \
      # --bucket theres-a-hole-in-the-bucket
      # bash -c 'aws --endpoint-url http://localhost:9000/ s3 mb s3://this-is-a-test-bucket' 