name: minio test harness
on: [ push ]
jobs:
  minio-startup:
    runs-on: ubuntu-latest
    steps:
      - name: startup minio
        uses: infleet/minio-action@v0.0.1
        with:
          port: "9000"
          version: "latest"
          username: "miniominio"
          password: "miniominio"
      - name: AWS CLI Action
        uses: KaMeHb-UA/aws-cli-action@v3
        with:
          command: |
            AWS_ACCESS_KEY_ID=miniominio 
            AWS_SECRET_ACCESS_KEY=miniominio 
            aws --endpoint-url http://localhost:9000/ s3 mb s3://this-is-a-test-bucket 
